### ISSUE TITLE
Can this play nicer with py.test?

### ISSUE THREAD

**Issue by jacebrowning** [garybernhardt/expecter#20]
I would like to use `expecter` along with `py.test` (and https://github.com/ropez/pytest-describe), but it seems that `py.test` thinks the call to `expect()` is part of my code and thus shows me the code around the `assert` statement within `expector` as "context" for the failure:

```
___________ describe_template.describe_get_path.returns_default_when_no_style ____________

template = <memegen.domain.template.Template object at 0x102767390>

    @patch('os.path.isfile', Mock(return_value=True))
    def returns_default_when_no_style(template):
>       expect(template.get_path()) == "abc/default2.png"

memegen/test/test_domain_template.py:24:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = expect('abc/default.png'), other = 'abc/default2.png'

    def __eq__(self, other):
        msg = 'Expected %s but got %s' % (repr(other), repr(self._actual))
        if (isinstance(other, basestring) and
                isinstance(self._actual, basestring)):
            msg += normalized_diff(other, self._actual)
        elif len(repr(self._actual)) > 74:
            msg += normalized_diff(pprint.pformat(other),
                                   pprint.pformat(self._actual))
>       assert self._actual == other, msg
E       AssertionError: Expected 'abc/default2.png' but got 'abc/default.png'
E       Diff:
E       @@ -1 +1 @@
E       -abc/default2.png
E       +abc/default.png

env/lib/python3.5/site-packages/expecter.py:55: AssertionError
```

Ideally, this these lines:

```
self = expect('abc/default.png'), other = 'abc/default2.png'

    def __eq__(self, other):
        msg = 'Expected %s but got %s' % (repr(other), repr(self._actual))
        if (isinstance(other, basestring) and
                isinstance(self._actual, basestring)):
            msg += normalized_diff(other, self._actual)
        elif len(repr(self._actual)) > 74:
            msg += normalized_diff(pprint.pformat(other),
                                   pprint.pformat(self._actual))
>       assert self._actual == other, msg
```

would be hidden and/or replaced with introspection into the **actual** code that caused the failure.

Is there a way to "teach" `py.test` that `expector.expect()` is also test code (that produces its own assertion information)?

**Comment by garybernhardt** [comment]
Short version: "I'd rather not." :)

Long version:

The "Writing well integrated assertion helpers" section [here](https://pytest.org/latest/example/simple.html) seems to indicate that it's possible to exclude functions from the traceback, theoretically including all of expecter's internals, by putting `__tracebackhide__ = True` inside them.

However, removing context from tracebacks makes them more opaque, which defeats one of expecter's goals (providing a pretty assertion interface without the feeling of "magic" that most have).

As for replacing expecter lines in the traceback with the actual code, that sounds like a project at least an order of magnitude more complex than expecter itself, and one that I don't think should be undertaken; or, at least, not widely used. That type of tool always seems like a good idea at the time. Then, five years later, the tool has a reputation for unreliable reporting. And, worse, programmers who grew up on it have been taught that programming tools are inherently unreliable.

If you really don't want expecter in the traceback, one possible workaround is to write your own function that wraps expect() mark it with py.test's `__tracebackhide__`. The larger question of replacing pieces of tracebacks may be answered by some part of py.test, or at least a plugin to it. It does a lot of things.

I'm going to close this because I don't think that this behavior belongs in expecter itself, but I hope some of that is useful.

**Comment by jacebrowning** [comment]
Thanks for the information! I'm going to try wrapping `expect()` to explore the behavior.

**Comment by jacebrowning** [comment]
From my investigation, wrapping `expecter` did not hide hide the traceback inside of `expect()`, but adding `__tracebackhide__` inside of `expect()` did: https://github.com/jacebrowning/expecter/commit/d76541fbd02a17b8eee29c47d7b10ee32cbd6f4b

Would you be open to a pull request that conditionally sets `__tracebackhide__` inside of `expecter`'s functions based on an environment variable? It seems that `pytest`'s debugger is only concerned with the truthiness of the `__tracebackhide__` local variable so something like:

``` python
__tracebackhide__ = os.getenv('EXPECTER_HIDETRACEBACK')
```

should default to `expecter`'s normal behavior.
